[tools]
"aqua:eza-community/eza" = "0.23.5"
"aqua:google-antigravity/antigravity-cli" = "1.1.24"
"aqua:helix-editor/helix" = "25.07.1"
"aqua:k1LoW/git-wt" = "0.29.1"
"aqua:rossmacarthur/sheldon" = "0.8.5"
ast-grep = "0.45.3"
aube = "v1.41.0"
bat = "0.26.1"
bun = "1.4.0"
claude = "2.1.258"
cloudflared = "2026.8.3"
codex = "0.153.4"
"conda:ffmpeg" = "8.1.1"
copilot = "v1.0.82"
cursor-agent = "2026.08.04-aaa8809"
delta = "0.19.2"
deno = "2.9.6"
fd = "10.4.2"
fzf = "0.74.3"
gcloud = "570.0.0"
gh = "2.98.0"
ghq = "1.10.1"
"github:babarot/gomi" = "v1.6.4"
"github:gfazioli/octoscope" = "v0.29.0"
"github:hayatosc/git-cx" = "0.2.0"
"github:microsoft/apm" = "v0.28.0"
"github:mizchi/actrun" = "0.29.0"
"github:steipete/gogcli" = "v0.37.0"
"github:zenbu-labs/terminal-browser" = "v0.6.0"
go = "1.27.1"
"go:golang.org/x/tools/gopls" = "v0.23.0"
imagemagick = "7.1.2_25"
jq = "1.8.2"
lazygit = "0.64.1"
moonbit = "0.10.7+bc794d341"
ni = "30.5.0"
node = "24.19.0"
"npm:agent-browser" = "0.34.0"
"npm:acpx" = "0.13.2"
"npm:@xai-official/grok" = "1.0.5"
"npm:bash-language-server" = "5.6.0"
"npm:typescript-language-server" = "6.0.0"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.24.0"
opencode = "1.18.26"
pnpm = "12.2.1"
portless = "0.15.5"
python = "3.14.7"
resvg = "0.48.1"
ripgrep = "15.2.0"
rtk = "v0.45.0"
rust = "1.98.0"
rust-analyzer = "2026-05-25"
starship = "1.26.0"
taplo = "0.10.0"
tmux = "3.6b"
ttyd = "1.7.7"
ty = "0.0.75"
uv = "0.12.5"
yarn = "4.18.0"
yazi = { version = "26.8.15", postinstall = "ya pkg install" }
zig = "0.16.0"
zoxide = "0.10.0"
"github:herdrdev/herdr" = "v0.8.2"
sd = "1.1.0"

[settings]
experimental = true
lockfile = true
minimum_release_age = "3d"
aqua.registry_cache_ttl = "1d"
fetch_remote_versions_timeout = "30s"

[env]
AUBE_ALLOWED_UNPOPULAR_PACKAGES = "acpx,portless"
EDITOR = "hx"
VISUAL = "hx"

[hooks]
postinstall = ""

[tasks.sync-codex]
description = "sync config.toml on .codex folder"
run = "bun ~/.config/zsh/scripts/codex-sync-config.ts"

[tasks.sync-antigravity]
description = "sync settings.json on .gemini/antigravity-cli folder"
run = "bun ~/.config/zsh/scripts/antigravity-sync-config.ts"
